https://tutorials.chainer.org/ja/05_Basics_of_Linear_Algebra.html#%E3%83%99%E3%82%AF%E3%83%88%E3%83%AB%E5%80%A4%E9%96%A2%E6%95%B0%E3%81%AE%E5%BE%AE%E5%88%86

In [38]:
import numpy as np
import pandas as pd
import scipy as sp
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

### ベクトルによる微分と勾配

In [39]:
x=np.array([3,4]).reshape(-1,1)
A=np.array([[1,2],[3,4]])

In [40]:
A

array([[1, 2],
       [3, 4]])

#### 右辺

In [44]:
np.dot(x.T,A+A.T)

array([[26, 47]])

In [45]:
A+A.T

array([[2, 5],
       [5, 8]])

In [46]:
np.add(A,A.T)

array([[2, 5],
       [5, 8]])

In [47]:
##

In [48]:
np.dot(np.dot(x.T,A),x)

array([[133]])