In [18]:
import numpy as np
import scipy as sp

In [19]:
sp.exp(1)

2.718281828459045

In [26]:
A=np.matrix([[1,2,3],
          [4,5,6]
         ])
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [27]:
sp.exp(A)

matrix([[  2.71828183,   7.3890561 ,  20.08553692],
        [ 54.59815003, 148.4131591 , 403.42879349]])

In [30]:
sp.exp(A[1,2])

403.4287934927351

In [23]:
sp.log(A)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

### ロジット変換で確かめてみる

In [49]:
Y=np.array([10,20,30,40,50])
Y=np.reshape(Y,(len(Y),1))
Y

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [50]:
X=np.array([
    np.ones(len(Y)),
    [5,6,7,8,9]
]).T
X

array([[1., 5.],
       [1., 6.],
       [1., 7.],
       [1., 8.],
       [1., 9.]])

In [51]:
x0=np.ones(len(Y))
x1=np.array([5,6,7,8,9])

In [52]:
shita=np.array([
    [5],
    [10]
])

In [54]:
xs=np.dot(X,shita)
xs

array([[55.],
       [65.],
       [75.],
       [85.],
       [95.]])

In [57]:
1/1+sp.exp(-xs)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [63]:
1/1+sp.exp(-(5+10*x1))

array([1., 1., 1., 1., 1.])

In [64]:
sp.log(Y)

array([[2.30258509],
       [2.99573227],
       [3.40119738],
       [3.68887945],
       [3.91202301]])